apiVersion: v1
kind: Config
currentContext: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
contexts:
  - context:
      cluster: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
      user: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
    name: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
clusters:
  - cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRZmo5ZXd1SFpEdVhBS2Z1MWxXdmR1ekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd1l6VmxZemd4TkMwMFl6UmpMVFJpWkRJdE9UbGlOQzFrT0RWa1ltSXdZbVV5WkRrdwpJQmNOTWpVeE1USTRNRGN5TVRNMVdoZ1BNakExTlRFeE1qRXdPREl4TXpWYU1DOHhMVEFyQmdOVkJBTVRKREJqCk5XVmpPREUwTFRSak5HTXROR0prTWkwNU9XSTBMV1E0TldSaVlqQmlaVEprT1RDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU1MK2ltL3NUb2NIdTMyQkNBUzBrOUxyUTQva2hKcTZXOFFsbktCdApaRklGUm1yZUhBcGFlNGRPSDMyYUt2ejR0TTVhNllBUlNoQmdkOGx3VUxzSlJHKzRtbFl5cVdUODYrUlRIUTVNCkEybC9CRkd5Ump4aHVMN1l2aVJzS0RGcmt4OGRnVHlreElxVGZaYnBRbjVRQVhOQUNqYzJrbG1pc3QzVHBPS3YKYldXWVlaaVEydG9Lam9EZnkwUjJDekxKdkNQbUwwc2NPU05qT1FnOW9lMmIyV3VROU5MVmdoQk04RlJsdkF0NwpITjZJUjZ6eHVoTnhuQkJObGhYdFhLc2RVa0J1bi8rZlVxTytTbzhCTFIwbHJyQmZibHppRjFjWTNzQWMzZTFQClpwMWNibXdxcG9pTnZCTnpzekJTdmNWdEU0UENhcks5SXdDNXpqZHlDb1B2OGJZV3FtMmlRRHY1NC9wekc3VUkKZjYxRFJNQnJYSnp3dG5EZGdzME9oNmtxeDdRQjNBRTRWb3hLcHJLcHNFQTRaa1NFb0hyU3dLcXZ1ZzFwbjhEdgpwU1VxSDEybkVqOFg1czhiZE9rU1RDMEUrUm8zd2t0cmhuVXVtWmNsenZKREZiU1paSGdmcTRVQTlYRE0vckRSCm84dDZSb1JPOWtmUWZaQnNBTmh0cDNEYzhRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVIWjFKVVpwWTFsTjd2VkNYMDd2SDl4VytFWk13RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFGL09tVDJFQXQ0Yzh0cGx2SWJRRzZUUVN4bXVVSVVEYmI0Q2YwbTV2SjY4Clg2TGVsQ2VGT2pPVFhSOGVpWnNGYVNZK0Zuai8wa1h6NmdFWVp0NC9BMllJbjRxa1M5UlNnbDBmaFplVzhPQ3IKTC9sMVJ1ZDcrdSsyZVlvSE1ZOTg4K3ZBR3hzQzhiWEJFVU1UQW9CUWZjcFp6NTkvSjA4dFdlNFAvWGcyR0lUTAptUzk5cThCOFk1TEw4T2E2WmJ3cHltZjRQOHFRaGV1MmY5eVlxcEpndUdjYkNHNld3eVFWYjYwbGEyYkNhTEQrCmR5WnlwMk5YQ28vQ3F3MTlNS2JjL1k2cXBkUUNpZ1lSYUZrMXNGT3pYODZTMVVWSUVFY0ExcTNjQmk1UU1OVkkKSjExcTNVZTlZR1QxRmg1TnVKKzFpd2dGZmxXZzhnUHhCVE5ZM2ViTVhhaGRVL2V1STRjeTdiUjEyTU1EbU02QgpteUl1aEZ1OWQ2S1FZanZjaGFoZDgzbTFqOW44M1kwck0zUEl6cTJaZXdOWDNFMkNkb214bS9RMFNiZkJxVTFlCis1RVkyOXV3Nmo4YSt2Ylg2SWY0NS9reFp2eHU0R3RZdGlsOCtnM0QzcksvV29qNjVoakpESGw1amNObTVIdjgKZktEUDZSQmw5Rkhud0thMVJLVTZqUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://10.45.0.2
    name: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
users:
  - name: gke_dview-gc_asia-south1-b_dview-gke-prod-cluster-01
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args: null
        command: gke-gcloud-auth-plugin
        env: null
        installHint: >-
          Install gke-gcloud-auth-plugin for use with kubectl by following
          https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
        interactiveMode: IfAvailable
        provideClusterInfo: true
