apiVersion: v1
kind: Config
currentContext: gke_dview-gc_asia-south1-b_test-ui
contexts:
  - context:
      cluster: gke_dview-gc_asia-south1-b_test-ui
      user: gke_dview-gc_asia-south1-b_test-ui
    name: gke_dview-gc_asia-south1-b_test-ui
clusters:
  - cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUlvS1AySEd5L2Y5amdqd2pKckk4TGt3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05tSmpOR00yWldJdE5HRmtaaTAwWTJNd0xUbGtZalF0TkRObE1qWTROVGN6TURJegpNQ0FYRFRJMk1EUXhNekV6TXpBMU0xb1lEekl3TlRZd05EQTFNVFF6TURVeldqQXZNUzB3S3dZRFZRUURFeVEyClltTTBZelpsWWkwMFlXUm1MVFJqWXpBdE9XUmlOQzAwTTJVeU5qZzFOek13TWpNd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDdmFFeEFwQnpNdlE4cFBZWjBFa0RWcTNiWHpUelFjaURLTHVxQwpuY3k4cjNMQzI3MDJCV2F0MlNHQ3l1NDVpbVVSYjNoOHFFSnMvbHVEa21wTGJ2Y0dJbFN5TmF3d0pvZ20wcjZHCmRLSkcyMFAvSHVabTAyVERDL2hIOFh3b0o5N2xiT1lkcE51SGVIc0hmTFl0TWdxV1FvU0x2RHd5N1FYVThPWFgKL3hWbUIzdTdtNG83VzdEZTZUZ3RKRWc0Z2hsaTcyM0NtTnpsMmJNQkJrYU5JVEo3b281TmpxaHVKanhqbUpSbQpuZkI4Z3RsU3o4REJ4anFJYm9CUWdaWDBJbHZOa2Jsd2tHdGV1WEU0U2hPcVU5bldGdzJiRzFuMU9Da3JQemxJCmNGR0hEQWpNWFZra2dMYTd0azBhckswQmhXbjVDVjBmRlYvTm5iR05QY2Jvc1FzT2svQlVxUE5IKy9jWjNSK2EKdWpHOFdaQ0pmZkVmQVFUd0tGVUdWUEQ2d1Q1WjhwOEhYclBocjZ0M2VKdkYrUXF6NW9tSktzelJGRU43WEpFbQpXY3E0Wk1zNGFXamlPeEpqVGI0cmpLcVVmakVnMDd6YUhGOFRqMWR5S0NPSmhoQ1FYeTl4MFhIMlZRWUVmeGx1CmxKNHRRRmUrOHJtS0NQOWQ0TUd5VWN5dHlEOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSVUvMzliNVc4bmdmbWNqYjI5M0M0dG5NWDJvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQWJjcG4zUjRSVUtab0o4WExSWThSWU53VDA3UjJiVTdtRnE5VnQwMFozCngrNUI0L0c1eVBRRU42aWhuTTRDUnNmazJhUXNYM1dvRE5hM3czYlc5dFRVT212SkkycE9FWmxqSjdjMU02VjAKNEdtdjFoYkxaSTV1QnpCY2d2TUN0UmpOQjZ1NXg1KzJ0c1ZzWXZLcHMzdzdqMDlGS0dONy9rMDdGK2o1RWNpYwpQVHhjY0k3OTdiV0hvZVZSQ0dxc3JrbGxWVjN1TnRBRWZkR0tBQm9ycm1BRW1hRWpwK2NUbk13TUpDdDEvVDkxCk5YUXJXVkNlbnZ0d1BDSmNYNCtZWnE4MWFrRmVvRlRjczBmQWt3d3JHR2lsMjdWVHNvWCtxNlFSVXpQRkQ3WXgKSjZwcXlodlJuRDVPZWk5VGVnY2pVeHFyejZUNVVZMTVlMzRNeHU3aW5oQTl6MnVDdjZ1eXdaZkpmbUF4bUU2dwpqbDBVY1Y2TjFSaGRsVy80ZXJsOXZ0ZmllUmR6NkdoYlhlbDlUUnd1RmhPNy9nMkJZS0tudXc3UzUxODNnUldMCi9LWVpxWU83c3gybkFrV013YTI2SnJqRGo3L2ZReDMzWEM1Z2hoUFFSR2c3T2F3emJndTlVSFRieWJiN0F6TC8KZFh5Z1JtWThJR3RCN1hXKzBUWkRCUTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://34.93.108.113
    name: gke_dview-gc_asia-south1-b_test-ui
users:
  - name: gke_dview-gc_asia-south1-b_test-ui
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: gke-gcloud-auth-plugin
        installHint: >-
          Install gke-gcloud-auth-plugin for use with kubectl by following
          https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
        provideClusterInfo: true
