apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRUVlSZzlZN3k5R200bWdDUHhENVJIVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSa09XUm1ZbUV6T1MxaU9UWTVMVFJoTURFdE9UTmhaaTA1WmpVd05HWmlZakJtWm1VdwpJQmNOTWpZd05EQXpNRFF3TXpJMFdoZ1BNakExTmpBek1qWXdOVEF6TWpSYU1DOHhMVEFyQmdOVkJBTVRKR1E1ClpHWmlZVE01TFdJNU5qa3ROR0V3TVMwNU0yRm1MVGxtTlRBMFptSmlNR1ptWlRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUwvRWREVndyY2I1QmhDQThjck1qVnZEY2RLc1lUOUY2S2FXL1I0OApzSGM0LzBteFVEYy9HbWpueHVta3NTMTg1TktOWDd5Nll3TlVHOEUrNzJxdUY5a211WENFUmtvdkp5cExwU3Q1ClpGLzh6enJpS0VTUVZuZkkxNW5qZnJDT3AzYUMwWFlKUDJkbjhIcks4K3NGUS9mQmNYZmtFcUNwL3dVNnZSWHIKZ3ZwRlA0cXV1SGpTdHV2OHN4WUJSQjVYcG1OdS8wRlFqRFpRaUx3QkFwVDZiVlN2cHJsNHFSWVBxN2MzZDVVVApjcWtGRC8xNnpGdFlDbEdQVXZJdjRhLzZCUmMvWVdsMlRkRCtTQTBibFpwMGRBMm5wdi9HcldMR3MvbVB4NFE3CldtemVkcEpudkVEaFNyV0JocmNCa3o5aExhMFM5NzJFSlQ0S3BVdmdWYjVINEpXN0JpMHdkTUEyemt3cVlMYmQKZ2o2WlFXZWdyMCtzd3NRcjcrMXFUcUNLb0tHTms5WWVEa2h3TDNNaFlSTi9GNUU4YjNSeTI5K00xaVdUOFVzbwpjQVc4dXhGaE91Z0dHL3dlS3dCOUJBZGpReGtyeE5QejBUcTVMajRnRENuVHJNbFR1S2d4THVMOERwL0o3T01TCjhTKzgwUm1HSjNOK2dzdkZ5OThDdXhnTVl3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV1UTgvUFM5TjUyNzE5SHN6aFZRdFkvMlVlYTR3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFMU2I3N0ROY2d3K3NnN3kzWWpIWlFuazJCS3lJNmt2S3BWVEVMVFVka0NOClBUWXpzaW9WeXBGOWZHS3BWODhHa3pYS1pScS9wZEZ5L1hqZFc2NTRQb2JZYXZWSHZvMFY5RGRoUWgzMnAwS24KZVp1bG9iYzI2ZHZzYzBTemRNd2x4ZzdRbzhTRzV0Lzh0dUtuaEllZWlXNWlLVGdWUlNQYzJOWnB5czVwUzVObwpPQUxvVmxNRTNlVEdZaUlMQXJpS3RqS3VmK3BQV0tObWtSY0J2bVZJTlY4QXlFeTRpRzNGeGNnbEUySktIL3E4Cm0rK2FXeENFb0lQc1Erd0E3T3Nwa0RrM08zRkJvaHFKbU0zUUxWWWFtZTMrc3ZkRStYQW9LTmZPRmc1aVcyYmQKK3RaZlI3WmVYbGRSL1daZ2NidTN5eXBWWFV5Q0pzODNjdmFuR0REblFPZi94dUYwc1M1QzA4UkZ2ZTlUbG9DRwpuWEpCUHNydWlsdk5jeS8xOG9BVFFiRUsrREdZVktjRUkxd0lLelFyaVdidzduLzJReUdVWWhHWmZZNUNFWVBjCkpqZTVoODU0TE1JcStXM09KTGlBYzNoOU5FdDdUWityL05CclM0dXhpWnJxR3ltK2RqRG0raW1DTXFjNVczLzcKaURBNmdqcTB0eUJCOXZ3S2ZrNTRyUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.100.157.0
  name: gke_dview-gc_asia-south1-b_test-ui
contexts:
- context:
    cluster: gke_dview-gc_asia-south1-b_test-ui
    user: gke_dview-gc_asia-south1-b_test-ui
  name: gke_dview-gc_asia-south1-b_test-ui
current-context: gke_dview-gc_asia-south1-b_test-ui
kind: Config
users:
- name: gke_dview-gc_asia-south1-b_test-ui
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
